app:
  version: 0.1
  executor:
    thread-name-prefix: GeneralExecutor
    core-pool-size: 4
    max-pool-size: 4
    queue-capacity: 500

spring:
  data:
    mongodb:
      host: 127.0.0.1 # Mongo server host. Cannot be set with URI.
      port: 27017 # Mongo server port. Cannot be set with URI.
      database: sample # Database name.
#      username: ' ' # Login user of the mongo server. Cannot be set with URI.
#      password: ' ' # Login password of the mongo server. Cannot be set with URI.
#      uri: mongodb://127.0.0.1:27017/ # Mongo database URI. Cannot be set with host, port and credentials.
#      field-naming-strategy: # Fully qualified name of the FieldNamingStrategy to use.
#      grid-fs-database: # GridFS database name.
#      authentication-database: # Authentication database name.
      repositories:
              type: auto # Type of Mongo repositories to enable.